### PR TITLE
add ability to customize the incrementation strategy of the project version number

### PR DESCRIPTION
**Pull request by gpouilloux**
Add ability to customize the incrementation strategy of the project version number
=======

Why this feature ?
-------

At Sigma Informatique, we use the **m2release-plugin** for many Java projects.
We also have Delphi projects and each are built using Maven.

In Java, our projects' version respects the following scheme : 
**major**.*minor*.patch

In Delphi, we must have 4 digits in our version number :
**major**.*minor*.patch.dummy

> « This version number is composed of 4 parts separated by periods and may include alpha characters » http://en.wikipedia.org/wiki/Microsoft_version_numbering

Maven default versioning strategy auto-increments the last digit of the version number.
As the m2release-plugin relies on Maven's versioning strategy to build the next version number, we are not able to choose which digit should be incremented for our Delphi projects.
The result is that the '*dummy*' digit is always incremented whereas we want the '*patch*' digit to be incremented.  (as it is done for our Java projects...)

----------

How did we implement it ?
-------

In order to enable the user to customize the versioning strategy, I added a configuration option in the "Advanced" box.

versioning_configuration

By default, this option is not activated. The user needs to go to the "Advanced" configuration box and to tick the option to enable this new feature.

We understand that we're overriding Maven's default behavior but it is really comfortable to be able to decide the versioning strategy directly within Jenkins.

----------

Please let me know if you have some questions.

Regards,
guillaume
Sigma Informatique

### CODE REVIEW

**Comment by jtnord** [comment]
Initial comment would be - did you look at the maven way of doing this?
http://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#projectVersionPolicyId

**Comment by gpouilloux** [comment]
Did not find any link to this parameter when looking at a version policy feature.
If really implemented, how do you use it ?
I understand the default value is 'default' but how can I create a version policy and call it using -DprojectVersionPolicyId=

**Comment by jtnord** [comment]
The provided implementations are viewable [here](https://github.com/apache/maven-release/tree/trunk/maven-release-policies).  Each is a component and has a unique "hint" which is the policyId.

You would need to create a policy and then add this as an extra dependency (or extension?) on the maven-release-plugin in your project pom.  I would suggest following up on the [maven users list](https://maven.apache.org/mail-lists.html).

**Comment by gpouilloux** [comment]
Thank you for redirecting me to some implementations.
I will try to deal with Maven for this feature as I understand that Jenkins is only calling Maven to get the next version number.

After validating that this is working for a sample project using command-line, I will check if Jenkins is able to use this custom version policy to fill in the fields *Release Version* and *Development version* with appropriate values.

**Comment by jtnord** [comment]
So jenkins won't be able to use this to fill in the versions but if all versioning is left to maven should work as expected.

**Comment by gpouilloux** [comment]
Hi jtnord,

I was not able to get any answer on the maven users list regarding my request.
Also, if Jenkins won't be able to use the custom version policy to fill in the versions, I'm afraid users will be confused.
- Jenkins (front-end) will show a version number (as it does in the current version)
- Maven (back-end) will use another version number
With my contribution, Jenkins and Maven will be on the same page.

What do you think ?

Thanks,
guillaume

**Comment by gpouilloux** [comment]
Hi jtnord,

We understand that our request is not enough generic to be merged into the plugin so we will just close this one.

Thanks for the time and effort,
guillaume

**Pull request closed without merging**
